### ISSUE TITLE
R package checklist

### ISSUE THREAD

**Issue by gvegayon** [UofUEpiBio/epiworldR#53]
# R Packages Checklist

## Technical requirements

Our goal is for all R packages under EpiForeSITE to have the following features:

- [x] Lives on GitHub.
- [x] Has appropriate [`LICENSE`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) file (see also [licensing](https://r-pkgs.org/license.html) from R Packages (2e)).
- [x] Documented with [`roxygen2`](https://roxygen2.r-lib.org) ([Rd2roxygen](https://cran.r-project.org/package=Rd2roxygen) converts `.Rd` files to `roxygen2`), including function descriptions, parameters and return values, details, examples, references, and links to other relevant functions.
- [x] Includes at least one [`rmarkdown`](https://cran.r-project.org/web/packages/rmarkdown/index.html) vignette with an extended example of package usage
- [x] Has a website using [pkgdown](https://pkgdown.r-lib.org).
- [x] Has tests using either [`tinytest`](https://cran.r-project.org/web/packages/tinytest/index.html) or [`testthat`](https://cran.r-project.org/web/packages/testthat/index.html).
- [x] Uses continuous integration (CI) (e.g., [GitHub Actions](./dev-tools/github-actions.md)) to:
    - [x] Run `R CMD check` on multiple system configurations.
    - [x] Create the package website.

## Advanced Package Checklist

Once the above checklist is completed, there are some additional package features that would be nice to have but are not required:

- [x] Published on CRAN (see [CRAN's submission checklist](https://cran.r-project.org/web/packages/submission_checklist.html)).
- [x] Uses [`pre-commit`](https://pre-commit.com) both as part of CI and for local development.
- [x] Has a [`NEWS.md`](https://style.tidyverse.org/news.html#before-release) file.
- [x] Has a `Containerfile` under [`.devcontainer`](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers).
- [x] Uses [GitHub's release system](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) to keep the latest version current.
- [x] Has [branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) that prevent direct commits to the principal branch (main or master).
- [x] Uses `codecov` or `coveralls` to release code coverage (via the [covr R package](https://covr.r-lib.org/reference/codecov.html)).

<sub>(Version [4d5bcbc](https://github.com/EpiForeSITE/software/blob/4d5bcbc8a62b5e56d641d0997cd1d6b4c12d2244/docs/r-pkg-checklist.md))</sub>

**Comment by apulsipher** [comment]
Already completed checklist
